services:
  - type: web
    name: matthew-backend
    env: python
    plan: free
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn chatbot:app --host 0.0.0.0 --port $PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000
    autoDeploy: true
    rootDir: backEnd

  - type: static
    name: portfolio-frontend
    buildCommand: ""
    staticPublishPath: .
    rootDir: frontEnd
