services:
  - type: web
    name: matthew-backend
    env: python
    plan: free
    buildCommand: pip install -r ../requirements.txt
    startCommand: python chatbot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
    rootDir: backEnd

  - type: static
    name: portfolio-frontend
    buildCommand: ""
    staticPublishPath: .
    rootDir: frontEnd
